name: Continuous Deployment

on:
    push:
        branches: [master]

jobs:
    cd:
        name: Run CD
        runs-on: ubuntu-latest

        # Grant GITHUB_TOKEN the permissions required to push changes to target branch
        permissions:
            contents: 'write'
            packages: 'write'
            actions: 'read'

        environment: actions
        steps:
            - name: Create GitHub App token
              uses: actions/create-github-app-token@v1
              id: app-token
              with:
                  app-id: ${{ vars.SYNTHQL_APP_ID }}
                  private-key: ${{ secrets.SYNTHQL_APP_PRIVATE_KEY }}

            - name: Checkout Git Repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  token: ${{ steps.app-token.outputs.token }}

            - name: Set up Node.js environment
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: yarn

            - name: Set up database
              run: |
                  chmod +x ./setup-db.bash
                  ./setup-db.bash

            - name: Cache yarn dependencies
              uses: actions/cache@v4
              with:
                  path: |
                      **/node_modules
                      .yarn/cache
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-

            - name: Install dependencies
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: yarn install

            - name: Run CI tasks
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: yarn ci

            # We use the name and email for the GitHub Actions bot, as provided via this link: https://api.github.com/users/github-actions%5Bbot%5D
            - name: Set Git user
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

            - name: Publish packages to NPM & update repository
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: yarn publish-minor-versions
